<?php

// This file is part of OpenSparrow - https://opensparrow.org
// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2024-2026 OpenSparrow Contributors
// Licensed under LGPL v3. See COPYING.LESSER file for details.

declare(strict_types=1);

return [
    'roles' => [
        'guest'  => null,
        'editor' => ['test', 'test'],
        'admin'  => ['testadmin', 'testadmin'],
    ],

    'volatile' => [
        '/"csrf_token"\s*:\s*"[^"]*"/'                              => '"csrf_token":"<token>"',
        '/"CSRF_TOKEN"\s*:\s*"[^"]*"/'                              => '"CSRF_TOKEN":"<token>"',
        '/window\.CSRF_TOKEN\s*=\s*"[^"]*"/'                        => 'window.CSRF_TOKEN = "<token>"',
        '/name="csrf-token"\s+content="[^"]*"/'                     => 'name="csrf-token" content="<token>"',
        '/name="csrf_token"\s+value="[^"]*"/'                       => 'name="csrf_token" value="<token>"',
        '/"(created_at|updated_at|changed_at|last_login|expires_at|ts)"\s*:\s*"[^"]*"/' => '"$1":"<time>"',
        '/\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}(\.\d+)?([+-]\d{2}(:?\d{2})?|Z)?/'      => '<time>',
        '/nonce="[^"]*"/'                                           => 'nonce="<nonce>"',
        '/\?v=[0-9a-f]{6,}/'                                        => '?v=<hash>',
        '#([A-Za-z]:)?[\\\\/][^"<>\s]*?[\\\\/](public|includes|templates|src|cron)[\\\\/]#'
            => '<root>/$2/',
    ],

    'cases' => [
        ['id' => 'notifications.count', 'path' => 'api/notifications.php?action=get_count'],
        ['id' => 'notifications.list', 'path' => 'api/notifications.php?action=get_list'],
        ['id' => 'notifications.unknown', 'path' => 'api/notifications.php?action=nope'],
        ['id' => 'notifications.default_action', 'path' => 'api/notifications.php'],
        ['id' => 'notifications.mark_read_bad_id', 'path' => 'api/notifications.php?action=mark_read',
            'method' => 'POST', 'json' => ['id' => 0]],
        ['id' => 'notifications.mark_read_unknown_id', 'path' => 'api/notifications.php?action=mark_read',
            'method' => 'POST', 'json' => ['id' => 999999]],
        ['id' => 'notifications.mark_read_no_csrf', 'path' => 'api/notifications.php?action=mark_read',
            'method' => 'POST', 'csrf' => false, 'json' => ['id' => 1]],

        ['id' => 'fk.missing_table', 'path' => 'api/fk.php', 'ajax' => true],
        ['id' => 'fk.unknown_table', 'path' => 'api/fk.php?table=__nope__&col=x', 'ajax' => true],
        ['id' => 'fk.no_ajax', 'path' => 'api/fk.php?table=__nope__&col=x'],

        ['id' => 'schema.get', 'path' => 'api/schema.php', 'ajax' => true],
        ['id' => 'schema.no_ajax', 'path' => 'api/schema.php'],
        ['id' => 'schema.include_hidden', 'path' => 'api/schema.php?include_hidden=1', 'ajax' => true],
        ['id' => 'schema.post_rejected', 'path' => 'api/schema.php', 'method' => 'POST', 'ajax' => true,
            'json' => []],

        ['id' => 'views.list', 'path' => 'api/views.php?action=list'],
        ['id' => 'views.unknown', 'path' => 'api/views.php?action=__nope__'],
        ['id' => 'views.data_missing_view', 'path' => 'api/views.php?action=data'],
        ['id' => 'views.data_unknown_view', 'path' => 'api/views.php?action=data&view=__nope__'],
        ['id' => 'views.data_real', 'path' => 'api/views.php?action=data&view=v_demo_crm_pipeline_report'],
        ['id' => 'views.data_real_level',
            'path' => 'api/views.php?action=data&view=v_demo_crm_pipeline_report&level=1'],
        ['id' => 'views.data_real_filtered',
            'path' => 'api/views.php?action=data&view=v_demo_crm_pipeline_report&filter_col=stage&filter_val=Won'],
        ['id' => 'views.data_real_empty_filter',
            'path' => 'api/views.php?action=data&view=v_demo_crm_pipeline_report&filter_col=stage&filter_val='],
        ['id' => 'views.data_bad_filter_col',
            'path' => 'api/views.php?action=data&view=v_demo_crm_pipeline_report&filter_col=bad-col&filter_val=x'],
        ['id' => 'views.config', 'path' => 'api/views.php?action=config'],
        ['id' => 'views.schemas', 'path' => 'api/views.php?action=schemas'],
        ['id' => 'views.sync', 'path' => 'api/views.php?action=sync'],
        ['id' => 'views.save_invalid_payload', 'path' => 'api/views.php?action=save', 'method' => 'POST',
            'json' => ['nope' => true]],
        ['id' => 'views.save_wrong_method', 'path' => 'api/views.php?action=save'],

        ['id' => 'print.list', 'path' => 'api/print.php?action=list'],
        ['id' => 'print.unknown', 'path' => 'api/print.php?action=__nope__'],
        ['id' => 'print.data_unknown', 'path' => 'api/print.php?action=data&print=__nope__'],
        ['id' => 'print.data_real', 'path' => 'api/print.php?action=data&print=crm_pipeline_report'],
        ['id' => 'print.data_real_param',
            'path' => 'api/print.php?action=data&print=crm_pipeline_report&p_stage=Won'],
        ['id' => 'print.data_real_empty_param',
            'path' => 'api/print.php?action=data&print=crm_pipeline_report&p_stage='],
        ['id' => 'print.param_options_real',
            'path' => 'api/print.php?action=param_options&print=crm_pipeline_report&key=stage'],
        ['id' => 'print.columns_unknown_view', 'path' => 'api/print.php?action=columns&view=__nope__'],
        ['id' => 'print.config', 'path' => 'api/print.php?action=config'],
        ['id' => 'print.param_options_unknown', 'path' => 'api/print.php?action=param_options&print=__nope__'],
        ['id' => 'print.save_invalid_payload', 'path' => 'api/print.php?action=save', 'method' => 'POST',
            'json' => ['nope' => true]],
        ['id' => 'print.save_bad_template_key', 'path' => 'api/print.php?action=save', 'method' => 'POST',
            'json' => ['prints' => ['bad key!' => []]]],
        ['id' => 'print.save_bad_block', 'path' => 'api/print.php?action=save', 'method' => 'POST',
            'json' => ['prints' => ['tpl' => ['blocks' => [['type' => '__nope__']]]]]],
        ['id' => 'print.save_wrong_method', 'path' => 'api/print.php?action=save'],

        ['id' => 'comments.list_missing', 'path' => 'api/comments.php?action=list'],
        ['id' => 'comments.list_unknown_table',
            'path' => 'api/comments.php?action=list&related_table=__nope__&related_id=1'],
        ['id' => 'comments.mine', 'path' => 'api/comments.php?action=mine'],
        ['id' => 'comments.counts', 'path' => 'api/comments.php?action=counts'],
        ['id' => 'comments.unknown', 'path' => 'api/comments.php?action=__nope__'],
        ['id' => 'comments.list_real',
            'path' => 'api/comments.php?action=list&related_table=contacts&related_id=1'],
        ['id' => 'comments.list_real_limited',
            'path' => 'api/comments.php?action=list&related_table=contacts&related_id=1&limit=5'],
        ['id' => 'comments.counts_real',
            'path' => 'api/comments.php?action=counts&related_table=contacts&related_ids=1,2,3'],
        ['id' => 'comments.counts_real_empty_ids',
            'path' => 'api/comments.php?action=counts&related_table=contacts&related_ids='],
        ['id' => 'comments.add_no_csrf', 'path' => 'api/comments.php', 'method' => 'POST', 'csrf' => false,
            'json' => ['action' => 'add', 'related_table' => 'contacts', 'related_id' => 1, 'body' => 'x']],
        ['id' => 'comments.add_unknown_table', 'path' => 'api/comments.php', 'method' => 'POST',
            'json' => ['action' => 'add', 'related_table' => '__nope__', 'related_id' => 1, 'body' => 'x']],
        ['id' => 'comments.add_empty_body', 'path' => 'api/comments.php', 'method' => 'POST',
            'json' => ['action' => 'add', 'related_table' => 'contacts', 'related_id' => 1, 'body' => '   ']],
        ['id' => 'comments.add_bad_record_id', 'path' => 'api/comments.php', 'method' => 'POST',
            'json' => ['action' => 'add', 'related_table' => 'contacts', 'related_id' => 0, 'body' => 'x']],
        ['id' => 'comments.delete_missing_id', 'path' => 'api/comments.php', 'method' => 'POST',
            'json' => ['action' => 'delete', 'id' => 0]],
        ['id' => 'comments.delete_unknown_id', 'path' => 'api/comments.php', 'method' => 'POST',
            'json' => ['action' => 'delete', 'id' => 999999]],

        ['id' => 'notes.list_missing', 'path' => 'api/notes.php?action=list'],
        ['id' => 'notes.list_unknown_table', 'path' => 'api/notes.php?action=list&table=__nope__&id=1'],
        ['id' => 'notes.list_records', 'path' => 'api/notes.php?action=list_records'],
        ['id' => 'notes.unknown', 'path' => 'api/notes.php?action=__nope__'],
        ['id' => 'notes.list_real', 'path' => 'api/notes.php?action=list&table=contacts&id=1'],
        ['id' => 'notes.list_records_real', 'path' => 'api/notes.php?action=list_records&table=contacts'],
        ['id' => 'notes.list_records_unknown', 'path' => 'api/notes.php?action=list_records&table=__nope__'],
        ['id' => 'notes.add_no_csrf', 'path' => 'api/notes.php', 'method' => 'POST', 'csrf' => false,
            'json' => ['action' => 'add', 'body' => 'x']],
        ['id' => 'notes.add_empty_body', 'path' => 'api/notes.php', 'method' => 'POST',
            'json' => ['action' => 'add', 'body' => '   ']],
        ['id' => 'notes.add_half_relation', 'path' => 'api/notes.php', 'method' => 'POST',
            'json' => ['action' => 'add', 'body' => 'x', 'related_table' => 'contacts']],
        ['id' => 'notes.add_unknown_relation', 'path' => 'api/notes.php', 'method' => 'POST',
            'json' => ['action' => 'add', 'body' => 'x', 'related_table' => '__nope__', 'related_id' => 1]],
        ['id' => 'notes.add_bad_reminder', 'path' => 'api/notes.php', 'method' => 'POST',
            'json' => ['action' => 'add', 'body' => 'x', 'reminder_date' => 'not-a-date']],
        ['id' => 'notes.add_past_reminder', 'path' => 'api/notes.php', 'method' => 'POST',
            'json' => ['action' => 'add', 'body' => 'x', 'reminder_date' => '2001-01-01T10:00']],
        ['id' => 'notes.update_missing_id', 'path' => 'api/notes.php', 'method' => 'POST',
            'json' => ['action' => 'update', 'id' => 0, 'body' => 'x']],
        ['id' => 'notes.update_unknown_id', 'path' => 'api/notes.php', 'method' => 'POST',
            'json' => ['action' => 'update', 'id' => 999999, 'body' => 'x']],
        ['id' => 'notes.delete_missing_id', 'path' => 'api/notes.php', 'method' => 'POST',
            'json' => ['action' => 'delete', 'id' => 0]],
        ['id' => 'notes.delete_unknown_id', 'path' => 'api/notes.php', 'method' => 'POST',
            'json' => ['action' => 'delete', 'id' => 999999]],

        ['id' => 'owners.mine', 'path' => 'api/owners.php?action=mine'],
        ['id' => 'owners.editors', 'path' => 'api/owners.php?action=editors'],
        ['id' => 'owners.get_missing', 'path' => 'api/owners.php?action=get'],
        ['id' => 'owners.get_unknown_table', 'path' => 'api/owners.php?action=get&table=__nope__&id=1'],
        ['id' => 'owners.unknown', 'path' => 'api/owners.php?action=__nope__'],
        ['id' => 'owners.get_real', 'path' => 'api/owners.php?action=get&table=contacts&id=1'],
        ['id' => 'owners.history_real', 'path' => 'api/owners.php?action=history&table=contacts&id=1'],
        ['id' => 'owners.get_bad_id', 'path' => 'api/owners.php?action=get&table=contacts&id=0'],
        ['id' => 'owners.set_no_csrf', 'path' => 'api/owners.php', 'method' => 'POST', 'csrf' => false,
            'json' => ['action' => 'set', 'table' => 'contacts', 'record_id' => 1, 'owner_id' => 1]],
        ['id' => 'owners.set_unknown_table', 'path' => 'api/owners.php', 'method' => 'POST',
            'json' => ['action' => 'set', 'table' => '__nope__', 'record_id' => 1, 'owner_id' => 1]],
        ['id' => 'owners.set_bad_record_id', 'path' => 'api/owners.php', 'method' => 'POST',
            'json' => ['action' => 'set', 'table' => 'contacts', 'record_id' => 0, 'owner_id' => 1]],
        ['id' => 'owners.set_bad_owner', 'path' => 'api/owners.php', 'method' => 'POST',
            'json' => ['action' => 'set', 'table' => 'contacts', 'record_id' => 1, 'owner_id' => 999999]],
        ['id' => 'owners.mass_set_no_rows', 'path' => 'api/owners.php', 'method' => 'POST',
            'json' => ['action' => 'mass_set', 'table' => 'contacts', 'owner_id' => 1, 'row_ids' => []]],
        ['id' => 'owners.mass_set_bad_rows', 'path' => 'api/owners.php', 'method' => 'POST',
            'json' => ['action' => 'mass_set', 'table' => 'contacts', 'owner_id' => 1, 'row_ids' => 'x']],
        ['id' => 'owners.mass_set_bad_owner', 'path' => 'api/owners.php', 'method' => 'POST',
            'json' => ['action' => 'mass_set', 'table' => 'contacts', 'owner_id' => 0, 'row_ids' => [1]]],

        ['id' => 'files.list', 'path' => 'api/files.php?action=list'],
        ['id' => 'files.get_config', 'path' => 'api/files.php?action=get_config'],
        ['id' => 'files.relations_config', 'path' => 'api/files.php?action=get_relations_config'],
        ['id' => 'files.related_unknown_table', 'path' => 'api/files.php?action=get_related_records&table=__nope__'],
        ['id' => 'files.unknown', 'path' => 'api/files.php?action=__nope__'],
        ['id' => 'files.related_real', 'path' => 'api/files.php?action=get_related_records&table=contacts'],
        ['id' => 'files.list_paged', 'path' => 'api/files.php?action=list&page=1&limit=5&sort=name&dir=asc'],
        ['id' => 'files.list_filtered', 'path' => 'api/files.php?action=list&type=image&search=a'],
        ['id' => 'files.list_bad_sort', 'path' => 'api/files.php?action=list&sort=__nope__&dir=__nope__'],
        ['id' => 'files.related_missing_table', 'path' => 'api/files.php?action=get_related_records'],
        ['id' => 'files.delete_no_csrf', 'path' => 'api/files.php', 'method' => 'POST', 'csrf' => false,
            'json' => ['action' => 'delete', 'uuid' => '00000000-0000-4000-8000-000000000000']],
        ['id' => 'files.delete_bad_uuid', 'path' => 'api/files.php', 'method' => 'POST',
            'json' => ['action' => 'delete', 'uuid' => 'not-a-uuid']],
        ['id' => 'files.delete_unknown_uuid', 'path' => 'api/files.php', 'method' => 'POST',
            'json' => ['action' => 'delete', 'uuid' => '00000000-0000-4000-8000-000000000000']],
        ['id' => 'files.mass_delete_empty', 'path' => 'api/files.php', 'method' => 'POST',
            'json' => ['action' => 'mass_delete', 'uuids' => []]],
        ['id' => 'files.mass_delete_bad_uuid', 'path' => 'api/files.php', 'method' => 'POST',
            'json' => ['action' => 'mass_delete', 'uuids' => ['nope']]],
        ['id' => 'files.mass_tag_no_tags', 'path' => 'api/files.php', 'method' => 'POST',
            'json' => ['action' => 'mass_tag', 'uuids' => ['00000000-0000-4000-8000-000000000000'],
                'tags' => '']],
        ['id' => 'files.update_meta_bad_uuid', 'path' => 'api/files.php', 'method' => 'POST',
            'json' => ['action' => 'update_meta', 'uuid' => 'nope', 'display_name' => 'x']],
        ['id' => 'files.update_meta_nothing', 'path' => 'api/files.php', 'method' => 'POST',
            'json' => ['action' => 'update_meta', 'uuid' => '00000000-0000-4000-8000-000000000000']],
        ['id' => 'files.upload_no_file', 'path' => 'api/files.php', 'method' => 'POST',
            'json' => ['action' => 'upload']],

        ['id' => 'rag.tags', 'path' => 'api/rag.php?action=tags'],
        ['id' => 'rag.files', 'path' => 'api/rag.php?action=files'],
        ['id' => 'rag.unknown', 'path' => 'api/rag.php?action=__nope__'],
        ['id' => 'rag.tags_wrong_method', 'path' => 'api/rag.php?action=tags', 'method' => 'POST',
            'json' => []],
        ['id' => 'rag.query_empty', 'path' => 'api/rag.php?action=query', 'method' => 'POST',
            'json' => ['query' => '   ']],
        ['id' => 'rag.query_too_long', 'path' => 'api/rag.php?action=query', 'method' => 'POST',
            'json' => ['query' => str_repeat('x', 2100)]],

        ['id' => 'mass_edit.get_rejected', 'path' => 'api/mass_edit.php?action=mass_edit_preview'],
        ['id' => 'mass_edit.preview_no_rows', 'method' => 'POST',
            'path' => 'api/mass_edit.php?action=mass_edit_preview',
            'json' => ['table' => 'contacts', 'column' => 'last_name', 'row_ids' => []]],
        ['id' => 'mass_edit.preview_wrong_key', 'method' => 'POST',
            'path' => 'api/mass_edit.php?action=mass_edit_preview',
            'json' => ['table' => 'contacts', 'column' => 'last_name', 'ids' => [1, 2]]],
        ['id' => 'mass_edit.preview_unknown_table', 'method' => 'POST',
            'path' => 'api/mass_edit.php?action=mass_edit_preview',
            'json' => ['table' => '__nope__', 'column' => 'last_name', 'row_ids' => [1]]],
        ['id' => 'mass_edit.preview_id_column', 'method' => 'POST',
            'path' => 'api/mass_edit.php?action=mass_edit_preview',
            'json' => ['table' => 'contacts', 'column' => 'id', 'row_ids' => [1]]],
        ['id' => 'mass_edit.preview_unknown_column', 'method' => 'POST',
            'path' => 'api/mass_edit.php?action=mass_edit_preview',
            'json' => ['table' => 'contacts', 'column' => '__nope__', 'row_ids' => [1]]],
        ['id' => 'mass_edit.preview_real', 'method' => 'POST',
            'path' => 'api/mass_edit.php?action=mass_edit_preview',
            'json' => ['table' => 'contacts', 'column' => 'last_name', 'row_ids' => [1, 2, 3, 6, 7]]],
        ['id' => 'mass_edit.apply_no_rows', 'method' => 'POST',
            'path' => 'api/mass_edit.php?action=mass_edit_apply',
            'json' => ['table' => 'contacts', 'column' => 'last_name', 'row_ids' => [], 'value' => 'x']],
        ['id' => 'mass_edit.duplicate_unknown_table', 'method' => 'POST',
            'path' => 'api/mass_edit.php?action=mass_duplicate',
            'json' => ['table' => '__nope__', 'row_ids' => [1]]],
        ['id' => 'mass_edit.delete_no_rows', 'method' => 'POST',
            'path' => 'api/mass_edit.php?action=mass_delete',
            'json' => ['table' => 'contacts', 'row_ids' => []]],
        ['id' => 'mass_edit.unknown_action', 'method' => 'POST',
            'path' => 'api/mass_edit.php?action=__nope__', 'json' => []],
        ['id' => 'data_cleanup.get_rejected', 'path' => 'api/data_cleanup.php?action=data_cleanup_preview'],
        ['id' => 'data_cleanup.preview_empty_find', 'method' => 'POST',
            'path' => 'api/data_cleanup.php?action=data_cleanup_preview',
            'json' => ['table' => 'contacts', 'column' => 'name', 'find' => '']],
        ['id' => 'data_cleanup.preview_unknown_table', 'method' => 'POST',
            'path' => 'api/data_cleanup.php?action=data_cleanup_preview',
            'json' => ['table' => '__nope__', 'column' => 'name', 'find' => 'x']],
        ['id' => 'data_cleanup.preview_unknown_column', 'method' => 'POST',
            'path' => 'api/data_cleanup.php?action=data_cleanup_preview',
            'json' => ['table' => 'contacts', 'column' => '__nope__', 'find' => 'x']],
        ['id' => 'data_cleanup.preview_real', 'method' => 'POST',
            'path' => 'api/data_cleanup.php?action=data_cleanup_preview',
            'json' => ['table' => 'contacts', 'column' => 'last_name', 'find' => 'a',
                'case_insensitive' => true, 'ignore_accents' => true]],
        ['id' => 'data_cleanup.preview_real_whole_word', 'method' => 'POST',
            'path' => 'api/data_cleanup.php?action=data_cleanup_preview',
            'json' => ['table' => 'companies', 'column' => 'name', 'find' => 'Sp. z o.o.',
                'whole_word' => true, 'replace' => 'Sp. z o. o.']],
        ['id' => 'data_cleanup.apply_empty_find', 'method' => 'POST',
            'path' => 'api/data_cleanup.php?action=data_cleanup_apply',
            'json' => ['table' => 'contacts', 'column' => 'name', 'find' => '']],
        ['id' => 'data_cleanup.apply_unknown_table', 'method' => 'POST',
            'path' => 'api/data_cleanup.php?action=data_cleanup_apply',
            'json' => ['table' => '__nope__', 'column' => 'name', 'find' => 'x']],
        ['id' => 'data_cleanup.unknown_action', 'method' => 'POST',
            'path' => 'api/data_cleanup.php?action=__nope__', 'json' => []],

        ['id' => 'clickstats.get_rejected', 'path' => 'api/clickstats.php'],
        ['id' => 'clickstats.post_no_csrf', 'path' => 'api/clickstats.php', 'method' => 'POST',
            'json' => ['events' => []], 'csrf' => false],
        ['id' => 'clickstats.put_rejected', 'path' => 'api/clickstats.php', 'method' => 'PUT',
            'json' => ['events' => []]],
        ['id' => 'clickstats.empty_events', 'path' => 'api/clickstats.php', 'method' => 'POST',
            'json' => ['events' => []]],
        ['id' => 'clickstats.one_event', 'path' => 'api/clickstats.php', 'method' => 'POST',
            'json' => ['events' => [['element' => 'Baseline Probe', 'page' => 'index.php',
                'table' => 'contacts', 'record_id' => 1]]]],
        ['id' => 'clickstats.unknown_table_event', 'path' => 'api/clickstats.php', 'method' => 'POST',
            'json' => ['events' => [['element' => 'Baseline Probe', 'table' => '__nope__']]]],

        ['id' => 'gateway.schema', 'path' => 'api.php?api=schema'],
        ['id' => 'gateway.list_missing_table', 'path' => 'api.php?api=list'],
        ['id' => 'gateway.list_unknown_table', 'path' => 'api.php?api=list&table=__nope__'],
        ['id' => 'gateway.dashboard', 'path' => 'api.php?api=dashboard'],
        ['id' => 'gateway.calendar', 'path' => 'api.php?api=calendar'],
        ['id' => 'gateway.board', 'path' => 'api.php?api=board'],
        ['id' => 'gateway.workflows', 'path' => 'api.php?api=workflows'],
        ['id' => 'gateway.unknown', 'path' => 'api.php?api=__nope__'],
        ['id' => 'gateway.list_real', 'path' => 'api.php?api=list&table=contacts'],
        ['id' => 'gateway.subtable_counts_real', 'path' => 'api.php?api=subtable_counts&table=contacts&id=1'],
        ['id' => 'gateway.patch_unknown_table', 'path' => 'api.php', 'method' => 'PATCH',
            'json' => ['table' => '__nope__', 'id' => 1, 'column' => 'x', 'value' => 'y']],
        ['id' => 'gateway.delete_unknown_table', 'path' => 'api.php', 'method' => 'DELETE',
            'json' => ['table' => '__nope__', 'id' => 1]],

        ['id' => 'page.index', 'path' => 'index.php'],
        ['id' => 'page.index_unknown_table', 'path' => 'index.php?table=__nope__'],
        ['id' => 'page.index_real_table', 'path' => 'index.php?table=contacts'],
        ['id' => 'page.index_array_table', 'path' => 'index.php?table[]=contacts'],
        ['id' => 'page.index_api_delegation', 'path' => 'index.php?api=schema'],
        ['id' => 'page.index_unknown_workflow', 'path' => 'index.php?workflow=__nope__'],
        ['id' => 'page.index_array_workflow', 'path' => 'index.php?workflow[]=__nope__'],
        ['id' => 'page.index_real_workflow', 'path' => 'index.php?workflow=wf_demo_crm_001'],
        ['id' => 'page.index_workflows_flag', 'path' => 'index.php?workflows'],
        ['id' => 'page.dashboard', 'path' => 'dashboard.php'],
        ['id' => 'page.board', 'path' => 'board.php'],
        ['id' => 'page.board_real', 'path' => 'board.php?board=0'],
        ['id' => 'page.board_array', 'path' => 'board.php?board[]=0'],
        ['id' => 'page.calendar', 'path' => 'calendar.php'],
        ['id' => 'page.views', 'path' => 'views.php'],
        ['id' => 'page.views_real', 'path' => 'views.php?view=v_demo_crm_pipeline_report'],
        ['id' => 'page.views_array', 'path' => 'views.php?view[]=v_demo_crm_pipeline_report'],
        ['id' => 'page.print', 'path' => 'print.php'],
        ['id' => 'page.print_real', 'path' => 'print.php?print=crm_pipeline_report'],
        ['id' => 'page.print_array', 'path' => 'print.php?print[]=crm_pipeline_report'],
        ['id' => 'page.files', 'path' => 'files.php'],
        ['id' => 'page.create_missing_table', 'path' => 'create.php'],
        ['id' => 'page.create_unknown_table', 'path' => 'create.php?table=__nope__'],
        ['id' => 'page.edit_missing_table', 'path' => 'edit.php'],
        ['id' => 'page.edit_unknown_table', 'path' => 'edit.php?table=__nope__&id=1'],
        ['id' => 'page.edit_bad_id', 'path' => 'edit.php?table=__nope__&id=abc'],

        ['id' => 'adm.unknown_action', 'path' => 'admin/api.php?action=__nope__'],
        ['id' => 'adm.missing_action', 'path' => 'admin/api.php'],
        ['id' => 'adm.users_list', 'path' => 'admin/api.php?action=users_list'],
        ['id' => 'adm.users_stats', 'path' => 'admin/api.php?action=users_stats'],
        ['id' => 'adm.user_tables_get', 'path' => 'admin/api.php?action=user_tables_get&user_id=1'],
        ['id' => 'adm.user_tables_get_array', 'path' => 'admin/api.php?action=user_tables_get&user_id[]=1'],
        ['id' => 'adm.user_policy_get', 'path' => 'admin/api.php?action=user_policy_get'],
        ['id' => 'adm.migrations_list', 'path' => 'admin/api.php?action=migrations_list'],
        ['id' => 'adm.health', 'path' => 'admin/api.php?action=health'],
        ['id' => 'adm.cron_log', 'path' => 'admin/api.php?action=cron_log&limit=5'],
        ['id' => 'adm.cron_log_array_limit', 'path' => 'admin/api.php?action=cron_log&limit[]=5'],
        ['id' => 'adm.cron_stats', 'path' => 'admin/api.php?action=cron_stats'],
        ['id' => 'adm.clickstats_load', 'path' => 'admin/api.php?action=clickstats_load'],
        ['id' => 'adm.clickstats_log', 'path' => 'admin/api.php?action=clickstats_log&page=2'],
        ['id' => 'adm.clickstats_log_filtered',
            'path' => 'admin/api.php?action=clickstats_log&element=btn&user=test&page=1'],
        ['id' => 'adm.clickstats_log_array_page', 'path' => 'admin/api.php?action=clickstats_log&page[]=2'],
        ['id' => 'adm.automations_list', 'path' => 'admin/api.php?action=automations_list'],
        ['id' => 'adm.automations_runs', 'path' => 'admin/api.php?action=automations_runs'],
        ['id' => 'adm.automations_runs_rule',
            'path' => 'admin/api.php?action=automations_runs&rule_id=__nope__'],
        ['id' => 'adm.etl_load', 'path' => 'admin/api.php?action=etl_load'],
        ['id' => 'adm.etl_target_schemas', 'path' => 'admin/api.php?action=etl_target_schemas'],
        ['id' => 'adm.etl_target_tables', 'path' => 'admin/api.php?action=etl_target_tables&schema=public'],
        ['id' => 'adm.etl_flow_load', 'path' => 'admin/api.php?action=etl_flow_load'],
        ['id' => 'adm.etl_flow_log', 'path' => 'admin/api.php?action=etl_flow_log&flow_id=__nope__'],
        ['id' => 'adm.rag_settings', 'path' => 'admin/api.php?action=rag_settings'],
        ['id' => 'adm.rag_aggregate_view_list', 'path' => 'admin/api.php?action=rag_aggregate_view_list'],
        ['id' => 'adm.list_m2m', 'path' => 'admin/api.php?action=list_m2m'],
        ['id' => 'adm.list_procedures', 'path' => 'admin/api.php?action=list_procedures'],
        ['id' => 'adm.list_icons', 'path' => 'admin/api.php?action=list_icons'],
        ['id' => 'adm.menu_config', 'path' => 'admin/api.php?action=menu_config'],
        ['id' => 'adm.config_get', 'path' => 'admin/api.php?action=get&file=menu'],
        ['id' => 'adm.config_get_missing_file', 'path' => 'admin/api.php?action=get'],
        ['id' => 'adm.anonymization_load', 'path' => 'admin/api.php?action=anonymization_load'],
        ['id' => 'adm.save_rejects_get', 'path' => 'admin/api.php?action=save'],
        ['id' => 'adm.users_add_rejects_get', 'path' => 'admin/api.php?action=users_add'],
        ['id' => 'adm.init_db_rejects_get', 'path' => 'admin/api.php?action=init_db'],
        ['id' => 'adm.save_no_csrf', 'path' => 'admin/api.php?action=save', 'method' => 'POST',
            'json' => ['nope' => true], 'csrf' => false],
        ['id' => 'adm.users_add_no_csrf', 'path' => 'admin/api.php?action=users_add', 'method' => 'POST',
            'json' => ['nope' => true], 'csrf' => false],
    ],
];
